# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eefb7121e00e3d82439ba0bd061d017b6090393e91529e720812a90c06c99a4fe551a0da400a0a3ddc5e756bc8708ef206c7d431f3976be79a72bc8c4fb06748

test:
  secret_key_base: cfeb6412a634b5e43f14e1a6b06463cb69fa4c37adcc940cc8b87a3ab04175fd64b5c8ec3cc93a18fcecbf8b19034352a5bed0f144464443b2d1edfc4adea5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
